Start translating part-five of the tutorial
horacioh/gatsby pull request #4
Opened 2019-09-17 16:33 UTC by jackbravo

Start the translation of part 5.

2019-09-18 22:59 UTC, horacioh requested changes
MUCHAS GRACIAS POR TU ESFUERZZO Y TIEMPO! 🙏🙏🙏🙏

te paso algunas de las recomendaciones para mejorar tu enorme trabajo. Creo que si intentamos que la documentación sea lo mas inclusiva y amigable posible (evitar palabras o frases muy elaboradas, dirigirnos directamente al lector -. nada de "usted", "su" o cosas así --, y pasarnos con formalidades) en general estarán bien las traducciones :)

de nuevo, MUCHAS GRACIAS! de mi parte y del equipod e Gatsby también 👍

2019-09-18 22:59 UTC, horacioh commented on docs/tutorial/part-five/index.md
> +En este tutorial aprenderás como jalar datos a tu sitio de Gatsby usando GraphQL y plugins de fuentes de datos. Sin embargo, antes de aprender acerca de estos plugins, será bueno saber cómo usar algo
"aprenderás como consumir datos a tu..."

2019-09-20 21:07 UTC, horacioh requested changes
quizas se pueda mejorar con estas recomendaciones? que te parece?

2019-09-20 21:07 UTC, horacioh commented on docs/tutorial/part-five/index.md
> +En este tutorial aprenderás como jalar datos a tu sitio de Gatsby usando GraphQL y plugins de fuentes de datos. Sin embargo, antes de aprender acerca de estos plugins, será bueno saber cómo usar algo
@jackbravo puedes cambiar "jalar"? gracias!

sorry @anblave, esto no lo habias traducido tu :)

2019-09-20 21:07 UTC, horacioh commented on docs/tutorial/part-five/index.md
> +Investiga con `Site` y ve que campos están disponibles dentro, incluyendo el `siteMetadata` que consultaste antes. `Site` es un "tipo" de dato incorporado en Gatsby. ¡Intenta abriendo GraphiQL y jueg
> Investiga con `Site` y ve que campos están disponibles dentro, incluyendo el `siteMetadata` que consultaste antes. `Site` es un "tipo" de dato incorporado en Gatsby.

puedes intentar otra version? la parte "Investiga con `Site`..." no queda muy clara??

2019-09-20 21:07 UTC, horacioh commented on docs/tutorial/part-five/index.md
> +El explorador de GraphiQL te permite construir consultas de manera interactiva, haciendo click en los campos y entradas disponibles, evitando el repetitivo proceso de escribir estas consultas mano.
El explorador ~de~ GraphiQL...
> ...evitando el repetitivo proceso de escribir estas consultas mano...

"evitando escribir estas consultas repetitivamente."

2019-09-27 00:49 UTC, horacioh commented
@jackbravo si quieres esperar a que el equipo de Gatsby decida como haremos las traducciones, y haces tu una PR al repo base?

gracias por tu gran trabajo!

2019-09-27 14:49 UTC, jackbravo commented
Hola @horacioh. Sip, igual y esperamos un poco. He andado un poco ocupado y por eso tampoco seguí traduciendo. Pero seguro en hacktoberfest retomamos ;-) 💪

2019-10-01 07:27 UTC, horacioh commented
@jackbravo ya han comentado que podemos traducir la web en [este](https://github.com:gatsbyjs/gatsby-es) repo! :)

puedes pasar esta traduccion a ese repo?

gracias!

2019-10-01 07:27 UTC, closed without merging